
<footer id="footer">

<div id="footerLeft">
<img src="images/footer.png" width="276" height="60" alt="" />
</div>
<div id="footerRight">
<p class="companyname">Shenzhen Li & Sen Co.,Limited</p>
<p>Factory Add: 6th Floor, Fengtian New Technology Industry Park, No.308, 
	Xuegang North Road, Longhua District , Shenzhen, Guangdong  Province, China.</p>
<!--
<ul>	
	<li class="company">Shenzhen Li & Sen Co.,Limited</li>
	 <li>Email: info@ledcen.com</li>
	<li>Skype: jiang.florence</li>
	<li>Mob.: +86-13480990151(What'App & Wechat)</li>
	<li>Tel: +86-755-27846432</li>
	<li>QQ: 1017343417</li> 
	<li>Factory Add: 6th Floor, Fengtian New Technology Industry Park, No.308, 
	Xuegang North Road, Longhua District , Shenzhen, Guangdong  Province, China.</li>
</ul>
-->
</div>

<div id="copyright">
<p>Copyright &#169; 2016 Shenzhen Li & Sen Co.,Limited. All Rights Reserved.</p>
<p></p>
</div>

<!-- 
<ul>
<li><a href="blog.html">blog</a></li>
<li>facebook</li>
<li>twitter</li>
<li>linkedin</li>
<li>g+</li>
<li>youtube</li>
<li>fa</li>
</ul> -->
</footer>