
<div id="topnav">
	<div id="topnavRight"><p>+86 755 27846432</p></div>
</div>

<nav id="nav">
<div id="navlogo"><img src="images/logoledcen.png" alt="LEDCEN"></div>
<div id="navtext">
<ul class="navlay1">
	<li class="current"><a href="#">Why Ledcen?</a></li>
	<li><a href="#">Products</a>
	<!-- <ul class="productdetail">
	<li>Clean room lighting series</li>
<li>Clean room LED panel light</li>
<li>White frame </li>
<li>SS frame </li>
</ul>
<ul class="productdetail">
<li>Commercial lighting series</li>
<li>LED flat panel light</li>
<li>2*2 /2*4/1*4</li>
<li>T8 tube light </li>
<li>2ft/4ft/8ft</li>
</ul>
<ul class="productdetail">
<li>Wall pack /shoe box</li>
<li>MCOB bulb/MR16/GU10 series</li>
<li>Growing lights</li></ul>
 -->
</li>
	<li><a href="#">Alibaba Shop</a></li>
	<li><a href="#">About Us</a></li>
	<li><a href="#">Join Us</a></li>
</ul>
</div>

</nav>